multicloudtest:
  pod_timeout_seconds: 300
  enabled: false
  # if spawn_pod is enabled, pods are deployed INSTEAD of cronjobs
  spawn_pod: false
  ssh:
    private_key: 
      name: "SSH_PRIVATE_KEY"
      path: "/config/private_key"
      value: DEFINED-IN-REGION-SECRETS
    public_key: 
      name: "SSH_PUBLIC_KEY"
      path: "/config/public_key.pub"
      value: DEFINED-IN-REGION-SECRETS
  image:
    name: multicloudtest 
    tag: DEFINED-IN-REGION-SECRETS
  pushgateway: pushgateway-infra.infra-monitoring.svc.cluster.local
  clouds:
    azure:
      name: azure
      tests: DEFINED-IN-REGION
      creds_json: DEFINED-IN-REGION
      env:
        - name: AZURE_APPLICATION_CREDENTIALS
          value: "/config/creds.json"
    gcp:
      name: gcp
      tests: DEFINED-IN-REGION
      creds_json: DEFINED-IN-REGION
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/config/creds.json"
global:
  domain: cloud.sap
  region: DEFINED-IN-REGION
