global:
  dbPassword: topSecret
  db_region: local
  region: test
  master_password: test
  osprofiler:
    jager:
      enabled: true

api:
  cloudAdminProjectId: default
  adminPassword: topSecret
  imageTag: myTag

cron:
  imageTag: myTag

osprofiler:
  jager:
    enabled: true
