{{- if .Values.multicloudtest.enabled }}
{{- if .Values.multicloudtest.spawn_pod }}
{{ $mct := $.Values.multicloudtest }}
{{- range $.Values.multicloudtest.clouds }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: multicloudtest-{{ .name }}
  namespace: cc3test
spec:
  selector: 
    matchLabels:
      app: multicloudtest
  template:
    metadata:
      labels:
        name: multicloudtest-{{ .name }}
        type: test
    spec:
      containers:
         - name: multicloudtest-{{ .name }}
           image: {{ required ".Values.global.registry variable missing" $.Values.global.registry }}/{{ required ".Values.multicloudtest.image.name variable missing" $.Values.multicloudtest.image.name }}:{{ required ".Values.multicloudtest.image.tag variable missing" $.Values.multicloudtest.image.tag }}
           command:
             - /usr/bin/pytest 
           args:
           - tests/test_compute.py
           - --backend={{ .name }}
           - --config
           - testconfig.yaml
           - --pushgateway
           - {{ $mct.pushgateway }}:9091
           env:
             {{- range .env }}
              - name: {{ .name }}
                value: {{ .value }}
             {{- end }}
              - name: {{ $.Values.multicloudtest.ssh.private_key.name }}
                  value: {{ $.Values.multicloudtest.ssh.private_key.path }}
              - name: {{ $.Values.multicloudtest.ssh.public_key.name }}
                  value: {{ $.Values.multicloudtest.ssh.public_key.path }}
           volumeMounts:
             - mountPath: /config
               name: creds
               readOnly: true
      volumes:
        - configMap:
            name: multicloudtest-creds-{{ .name }}
          name: creds
{{- end}}
{{- end}}
{{- end}}
